apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccsa-recommend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccsa-recommend
  template:
    metadata:
      labels:
        app: ccsa-recommend
    spec:
      imagePullSecrets:
      - name: acr-credentials
      containers:
      - name: ccsa-recommend
        image: chancog.azurecr.io/ccsa_recommend:v0.1.1
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ccsa-recommend-service
spec:
  selector:
    app: ccsa-recommend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer