# Generated by Django 4.2.6 on 2023-10-13 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Convo",
            fields=[
                (
                    "convo_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Snippet",
            fields=[
                (
                    "snippet_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "snippet_type",
                    models.CharField(
                        choices=[
                            ("FRAMING", "FRAMING"),
                            ("ASSISTANT MESSAGE", "ASSISTANT MESSAGE"),
                            ("USER MESSAGE", "USER MESSAGE"),
                            ("LLM MESSAGE", "LLM MESSAGE"),
                        ],
                        max_length=200,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateField(blank=True, null=True)),
                (
                    "convo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suggestions.convo",
                    ),
                ),
            ],
        ),
    ]
