# Generated by Django 4.2.6 on 2023-10-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0002_snippet_is_initiate_alter_convo_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="convo",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="convo",
            name="updated_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
