# Generated by Django 4.2.6 on 2023-10-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0003_convo_created_date_convo_updated_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="pydantic_text",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
