# Generated by Django 4.2.6 on 2023-11-22 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0004_snippet_pydantic_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateField(blank=True, null=True)),
                (
                    "snippet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_bundles",
                        to="suggestions.snippet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("quality", models.CharField(blank=True, max_length=100, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateField(blank=True, null=True)),
                (
                    "match_bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_matches",
                        to="suggestions.matchbundle",
                    ),
                ),
            ],
        ),
    ]
