apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-redis-deployment
  template:
    metadata:
      labels:
        app: k8s-redis-deployment
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-redis-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: k8s-redis-deployment
