# Generated by Django 4.2.6 on 2023-10-08 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie", old_name="thubmnail", new_name="thumbmnail",
        ),
    ]
