# Generated by Django 4.2.6 on 2023-10-08 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_rename_thubmnail_movie_thumbmnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie", old_name="thumbmnail", new_name="thumbnail",
        ),
    ]
