# Generated by Django 4.2.6 on 2023-10-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_genre_movie_age_start_movie_genre"),
    ]

    operations = [
        migrations.RemoveField(model_name="movie", name="genre",),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(blank=True, null=True, to="movies.genre"),
        ),
    ]
