# Generated by Django 4.2.6 on 2023-10-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_remove_movie_genre_movie_genres"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="long_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="short_description",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="channels",
            field=models.ManyToManyField(blank=True, null=True, to="movies.channel"),
        ),
    ]
