# Generated by Django 4.2.6 on 2023-10-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_channel_movie_long_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="short_description",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
