# Generated by Django 4.2.6 on 2023-10-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_alter_movie_short_description_alter_movie_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="age_start",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
