# Generated by Django 4.2.6 on 2023-10-21 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_alter_movie_age_start"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
                ("image_b64_small", models.BinaryField(blank=True, null=True)),
                ("image_b64_medium", models.BinaryField(blank=True, null=True)),
                ("image_b64_large", models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="movie_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.movieimage",
            ),
        ),
    ]
