# Generated by Django 4.2.6 on 2023-10-23 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0009_movieimage_alter_movie_title_alter_movie_year_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="movie", name="movie_image",),
        migrations.DeleteModel(name="MovieImage",),
    ]
