# Generated by Django 4.2.6 on 2023-12-20 01:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0010_remove_movie_movie_image_delete_movieimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="call_diagnostics",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="cosmos_item_info",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="movie", name="item_info", field=models.JSONField(null=True),
        ),
        migrations.RemoveField(model_name="movie", name="genres",),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
