apiVersion: v1
kind: Service
metadata:
  name: ccsa-recommend-service
spec:
  selector:
    app: ccsa-recommend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer