apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccsa-recommend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccsa-recommend
  template:
    metadata:
      labels:
        app: ccsa-recommend
    spec:
      imagePullSecrets:
        - name: acr-credentials
      containers:
        - name: ccsa-recommend
          image: chancog.azurecr.io/ccsa_recommend:v0.1.3
          imagePullPolicy: Always  # Ensures the latest image is always pulled
          ports:
            - containerPort: 8000
          env:  # Specify each environment variable individually
            - name: ENV_ALLOWED_HOST
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: ENV_ALLOWED_HOST
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: DEBUG
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: POSTGRES_PORT
            - name: GPT35_DEPLOY_NAME
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: GPT35_DEPLOY_NAME
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: SECRET_KEY
            - name: DB_IGNORE_SSL
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: DB_IGNORE_SSL
            - name: COSMOS_URL
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: COSMOS_URL
            - name: COSMOS_KEY
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: COSMOS_KEY
            - name: COSMOS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: COSMOS_DB_NAME
            - name: AZURE_OPENAI_KEY
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: AZURE_OPENAI_KEY
            - name: AZURE_OPENAI_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: AZURE_OPENAI_ENDPOINT
            - name: TVDB_KEY
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: TVDB_KEY
            - name: PINECONE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: PINECONE_API_KEY
            - name: PINECONE_ENV
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: PINECONE_ENV
---
apiVersion: v1
kind: Service
metadata:
  name: ccsa-recommend-service
spec:
  selector:
    app: ccsa-recommend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer